### PR TITLE
Hacktober Commit

### PR DESCRIPTION
**Pull request by pingrishabh**
Used Recursion To Change The Color Every 3 Seconds For 10 Cycles Using Counters.

### CODE REVIEW

**Comment by sambhav2612** [comment]
I can't merge this PR, you have changed 314 files of which I do not know if it'll work on my system anymore.

However, if possible please attach the required code (only that method) here so that I can do the necessary.

**Comment by pingrishabh** [comment]
No buddy. It doesn't work like that. The contribution won't be counted that
way. You have to merge it. Of course It'll work. You just have to choose
yes whenever it asks you for upgrades. Keep your Android Studio updated and
you won't face any problem.

**Comment by sambhav2612** [comment]
the project structure remains same, right? If yes, I'm gonna approve this and merge. 
Thanks for your contribution, buddy.

**Comment by sambhav2612** [comment]
One more thing, add yourself to ```CONTRIBUTORS.md``` on ```master```. Thanks!

**Comment by pingrishabh** [comment]
Yes. I assure you. The project structure would absolutely be the same. And I'm here anyway. You face any further problems and I'll be more than happy to help you out.

**Comment by sambhav2612** [comment]
Great!

**Review by sambhav2612 — APPROVED** [review]

**Pull request merged**
